#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# MAFO AABO Trust™ — Hetzner VPS Deploy Script (Phase 0)
#
# Usage:
#   ./deploy-hetzner.sh [domain]
#   ./deploy-hetzner.sh trust.solvy.cards       # default
#
# First-time VPS setup (run once as root on VPS):
#   sudo -u postgres createdb mafo_aabo
#   sudo -u postgres createuser mafo --pwprompt
#   # DNS (solvy.cards zone): A record trust.solvy.cards → 46.62.235.95
#   # (via Replit support until zone access is restored — TASK-110)
#
# After first deploy, seed users + trust_settings over SSH (codes via private channel):
#   ssh -i ~/.ssh/hetzner_key root@46.62.235.95
#   cd /var/www/mafo-aabo && set -a && . ./.env && set +a && \
#     SEED_CODE_TRUSTEE=... SEED_CODE_GRANTOR=... SEED_CODE_BENEFICIARY=... node scripts/seed.js
#
# Run from:  mafo-aabo-server/  directory
# SSH key:   ~/.ssh/hetzner_key  (never share with any app/agent)
# ─────────────────────────────────────────────────────────────────────────────

set -e

DOMAIN="${1:-trust.solvy.cards}"
VPS="root@46.62.235.95"
# Use ~/.ssh/hetzner_key if present, otherwise fall back to the default SSH key/agent
if [ -f "$HOME/.ssh/hetzner_key" ]; then
  SSH_KEY="$HOME/.ssh/hetzner_key"
  SSH_I=(-i "$SSH_KEY")
else
  SSH_KEY="(default SSH key)"
  SSH_I=()
fi
APP_DIR="/var/www/mafo-aabo"      # backend lives here
WEB_DIR="/var/www/$DOMAIN"        # static frontend here

BOLD='\033[1m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
RED='\033[0;31m'; BLUE='\033[0;34m'; NC='\033[0m'

banner() { echo -e "\n${BLUE}${BOLD}▶ $1${NC}"; }
ok()     { echo -e "  ${GREEN}✓ $1${NC}"; }
warn()   { echo -e "  ${YELLOW}⚠ $1${NC}"; }
die()    { echo -e "  ${RED}✗ $1${NC}"; exit 1; }

echo -e "${BLUE}${BOLD}"
echo "  ╔══════════════════════════════════════════════╗"
echo "  ║   MAFO AABO Trust™ — Hetzner VPS Deploy     ║"
echo "  ║   Target: $DOMAIN"
echo "  ╚══════════════════════════════════════════════╝"
echo -e "${NC}"

# ── 1. Pre-flight ─────────────────────────────────────────────────────────────
banner "1/6  Pre-flight checks"

[ -f "server.js" ] || die "Run from the mafo-aabo-server/ directory"
[ -f "../solvy-platform/mafo-aabo/index.html" ] || die "Frontend not found at ../solvy-platform/mafo-aabo/"

ssh "${SSH_I[@]}" -o ConnectTimeout=8 -o BatchMode=yes "$VPS" "echo ok" &>/dev/null \
  || die "Cannot reach VPS. Check key and host."
ok "VPS reachable at 46.62.235.95"

# ── 2. Upload frontend ────────────────────────────────────────────────────────
banner "2/6  Uploading frontend → $WEB_DIR"

ssh "${SSH_I[@]}" "$VPS" "mkdir -p $WEB_DIR"
rsync -az --delete -e "ssh" ../solvy-platform/mafo-aabo/ "$VPS:$WEB_DIR/"
ok "Static files uploaded"

# ── 3. Upload backend ─────────────────────────────────────────────────────────
banner "3/6  Uploading backend → $APP_DIR"

ssh "${SSH_I[@]}" "$VPS" "mkdir -p $APP_DIR"
rsync -az --delete -e "ssh" \
  --exclude node_modules --exclude .env --exclude tests \
  ./ "$VPS:$APP_DIR/"

ssh "${SSH_I[@]}" "$VPS" "
  set -e
  cd $APP_DIR
  npm install --omit=dev --prefer-offline 2>&1 | tail -5
  echo 'npm install done'
"
ok "Backend uploaded and dependencies installed"

# ── 4. Configure .env (first time only) ──────────────────────────────────────
banner "4/6  Environment configuration"

ssh "${SSH_I[@]}" "$VPS" "
  if [ ! -f $APP_DIR/.env ]; then
    cat > $APP_DIR/.env << 'ENV'
# MAFO AABO Trust™ — Production Environment
NODE_ENV=production
PORT=3002
TRUST_DOMAIN=$DOMAIN
WEB_DIR=$WEB_DIR

# PostgreSQL (dedicated trust database)
DATABASE_URL=postgresql://mafo:CHANGE_ME@localhost:5432/mafo_aabo

# generate: openssl rand -hex 32
SESSION_SECRET=CHANGE_ME
ENV
    echo 'CREATED .env — edit it now:'
    echo '  ssh -i ~/.ssh/hetzner_key root@46.62.235.95 nano $APP_DIR/.env'
  else
    echo '.env already exists — skipping (edit manually if needed)'
  fi
"
ok "Environment file ready"

# ── 5. Start / reload PM2 service ────────────────────────────────────────────
banner "5/6  Starting PM2 service"

ssh "${SSH_I[@]}" "$VPS" "
  set -e
  cd $APP_DIR
  pm2 describe mafo-api > /dev/null 2>&1 \
    && pm2 reload mafo-api \
    || pm2 start pm2.config.cjs
  pm2 save
  echo '--- pm2 status ---'
  pm2 list
"
ok "PM2 service running on port 3002"

# ── 6. Configure Nginx ────────────────────────────────────────────────────────
banner "6/6  Configuring Nginx"

ssh "${SSH_I[@]}" "$VPS" "cat > /etc/nginx/sites-available/$DOMAIN" << NGINX
# MAFO AABO Trust™ — $DOMAIN
# Generated by mafo-aabo-server/deploy-hetzner.sh on $(date)

server {
    listen 80;
    server_name $DOMAIN;
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl http2;
    server_name $DOMAIN;

    ssl_certificate     /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;

    add_header Strict-Transport-Security "max-age=63072000" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;

    root  $WEB_DIR;
    index index.html;

    # API → mafo-api on port 3002
    location /api/mafo/ {
        proxy_pass         http://127.0.0.1:3002;
        proxy_http_version 1.1;
        proxy_set_header   Host \$host;
        proxy_set_header   X-Real-IP \$remote_addr;
        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_read_timeout 30s;
    }

    location / {
        try_files \$uri \$uri/ /index.html;
    }

    access_log /var/log/nginx/${DOMAIN}-access.log;
    error_log  /var/log/nginx/${DOMAIN}-error.log;
}
NGINX

ssh "${SSH_I[@]}" "$VPS" "
  set -e
  ln -sf /etc/nginx/sites-available/$DOMAIN /etc/nginx/sites-enabled/$DOMAIN

  if [ ! -f /etc/letsencrypt/live/$DOMAIN/fullchain.pem ]; then
    echo 'Obtaining SSL certificate for $DOMAIN...'
    cat > /etc/nginx/sites-available/$DOMAIN << TMP
server { listen 80; server_name $DOMAIN; root $WEB_DIR; location / { try_files \$uri /index.html; } }
TMP
    nginx -t && systemctl reload nginx
    certbot certonly --nginx -d $DOMAIN \
      --non-interactive --agree-tos --email admin@ebl.beauty \
      --redirect || true
  fi

  nginx -t && systemctl reload nginx
  echo 'Nginx configured'
"
ok "Nginx configured for https://$DOMAIN"

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}╔══════════════════════════════════════════════╗"
echo "║         Deployment complete!                ║"
echo -e "╚══════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  Live URL : ${BLUE}https://$DOMAIN${NC}"
echo -e "  API test : ${BLUE}https://$DOMAIN/api/mafo/health${NC}"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "  1. Fill in .env on the VPS (DATABASE_URL, SESSION_SECRET):"
echo "       ssh -i $SSH_KEY $VPS 'nano $APP_DIR/.env'"
echo ""
echo "  2. Seed the three users + trust_settings (codes from private channel):"
echo "       ssh -i $SSH_KEY $VPS 'cd $APP_DIR && set -a && . ./.env && set +a && \\"
echo "         SEED_CODE_TRUSTEE=... SEED_CODE_GRANTOR=... SEED_CODE_BENEFICIARY=... node scripts/seed.js'"
echo ""
echo "  3. Reload backend:"
echo "       ssh -i $SSH_KEY $VPS 'pm2 reload mafo-api && pm2 logs mafo-api'"
echo ""
echo -e "  ${BLUE}Keep ~/.ssh/hetzner_key on your local machine only.${NC}"
